export default {
  borderRadius: {
    borderRadiusNone: '0',
    borderRadiusSM: '6px',
    borderRadiusMD: '12px',
    borderRadiusLG: '18px',
    borderRadiusXL: '24px',
    borderRadiusCircle: '50%',
  },
  font: {
    family:
      "Poppins, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif",
    light: 300,
    normal: 400,
    semiBold: 600,
    bold: 700,
    sizes: {
      xxsmall: '1rem',
      xsmall: '1.2rem',
      small: '1.4rem',
      medium: '1.6rem',
      large: '1.8rem',
      xlarge: '2.0rem',
      xxlarge: '2.4rem',
      xxxlarge: '2.8rem',
      huge: '3.0rem',
      xhuge: '3.4rem',
      xxhuge: '3.8rem',
      xxxhuge: '4.2rem',
    },
  },
  gradient: {
    gradientColorBottom:
      'linear-gradient( to bottom, #f44336 0%, #5e35b1 100%)',
    gradientColorLeft: 'linear-gradient( to left, #f44336 0%, #5e35b1 100%)',
    gradientGreyBottom: 'linear-gradient( to bottom, #818386 0%, #aaa)',
  },
  grid: {
    container: '130rem',
    gutter: '2.4rem',
  },
  sizes: {
    xsmall: '1.2rem',
    small: '1.4rem',
    medium: '1.6rem',
    large: '1.8rem',
    xlarge: '2.0rem',
    xxlarge: '2.4rem',
    xxxlarge: '2.8rem',
    huge: '3.0rem',
    xhuge: '3.4rem',
    xxhuge: '3.8rem',
    xxxhuge: '4.2rem',
  },
  lineHeight: {
    lineHeightSM: '100%',
    lineHeightMD: '110%',
    lineHeightLG: '120%',
    lineHeightUL: '150%',
  },
  colors: {
    primary: '#000',
    secondary: '#F5DFDA',
    warning: '#ffae00',
    alert: '#cc4b37',
    tag: '#c2d6dc',
    success: '#3adb76',
    mainBg: '#06092B',
    lightBg: '#F2F2F2',
    white: '#FAFAFA',
    black: '#030517',
    lightGray: '#EAEAEA',
    gray: '#8F8F8F',
    darkGray: '#2E2F42',
  },
  spacings: {
    xxsmall: '0.8rem',
    xsmall: '1.6rem',
    small: '2.4rem',
    medium: '3.2rem',
    large: '4.0rem',
    xlarge: '4.8rem',
    xxlarge: '5.6rem',
  },
  layers: {
    base: 10,
    menu: 20,
    overlay: 30,
    modal: 40,
    alwaysOnTop: 50,
  },
  screen: {
    screenXS: '425px',
    screenSM: '768px',
    screenMD: '1000px',
    screenLG: '1400px',
    screenXL: '2560px',
  },
  transition: {
    default: '0.3s ease-in-out',
    fast: '0.1s ease-in-out',
  },
  breakpoints: {
    device: {
      mobileS: '(max-width: 320px)',
      mobileM: '(max-width: 375px)',
      mobileL: '(max-width: 425px)',
      tablet: '(max-width: 768px)',
      laptop: '(max-width: 768px)',
      laptopL: '(max-width: 1024px)',
      desktop: '(max-width: 1440px)',
      desktopL: '(max-width: 2560px)',
    },
  },
};
